name: "create-release"

on:
  push:
    branches:
      - "main"

jobs:
  create-release:
    name: "Create Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Create release"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
