on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  release-windows-386:
    name: release windows/386
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: windows
          goarch: 386
